import '../../styles/styles.scss'

export const metadata = {
  title: 'Create Next App sdsdfsd',
  description: 'Generated by create next app'
}

function Layout ({ children }: { children: React.ReactNode }) {
  return (
    <>
      <div>
        Layout for AUTHENTICATION
        {children}
      </div>
    </>
  )
}

export default Layout
